### ISSUE TITLE
Vulnerable

### ISSUE THREAD

**Issue by Rahuletto** [ArmoredVortex/Password-Generator#1]
This type of randomizing is very vulnerable (usage of Math.random()

> Note: Math.random() does not provide cryptographically secure random numbers. Do not use them for anything related to security. Use the Web Crypto API instead, and more precisely the window.crypto.getRandomValues() method.

Source: [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#:~:text=Note%3A%20Math.random()%20does,.crypto.getRandomValues()%20method.)

**Comment by ArmoredVortex** [comment]
6e69dd7892e5b670bae9af6ee5a4e838dd816939 Using window.crypto.getRandomValues() instead of Math.Random() as mentioned in the MDN docs
